version: '3'
services:
  seisan:
    container_name: seisan
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "../src:/var/www/html"
    tty: true
    depends_on:
      - db

  db:
      platform: linux/x86_64
      image: mysql:5.7
      container_name: seisan-db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: seisan
        MYSQL_PASSWORD: root
        TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - 3306:3306

  phpmyadmin:
    container_name: seisan-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=seisan-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
