version: '3'
services:
  seisan:
    container_name: seisan
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - "../src:/var/www/html"
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
    tty: true