version: '3'
services:
  seisan:
    container_name: seisan
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "../src:/var/www/html"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true