version: '3'
services:
  seisan:
    container_name: seisan
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
      - "24678:24678"
    volumes:
      - "../src:/var/www/html"
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
    tty: true
  # ngrok:
  #   container_name: ngrok
  #   image: wernight/ngrok:latest
  #   ports:
  #     - ${NGROK_PORT:-4040}:4040
  #   environment:
  #     NGROK_PORT: seisan:3000
  #     NGROK_AUTH: ${NGROK_AUTH}